---
title: "R Notebook"
output: html_notebook
---

```{r}
thisPath <- "C:/github/ApsimX/Prototypes/DEROPAPY"

thisFile <- "P019_MBIEClimateChangeEconomics_hrajab_2024-03-27.db"

thisPath <- "C:/github/ApsimX/Prototypes/DEROPAPY/outputs"

thisFile <- "P019_MBIEClimateChangeEconomics_hrlxxy_2024-09-09.db"
```

```{r}
regions_csv<-read.csv2("C:/github/ShinyClimateChange/Projects/GlobalParameters/vcsn_nz_region.csv", sep=",")
```

# Read Deropapy outputs
```{r}
# Install necessary packages if not already installed
if (!requireNamespace("DBI", quietly = TRUE)) install.packages("DBI")
if (!requireNamespace("RSQLite", quietly = TRUE)) install.packages("RSQLite")

# Load libraries
library(DBI)
library(RSQLite)
library(tidyverse)

```

```{r}
# Connect to the database
# Replace 'my_database.sqlite' with your database file path
db_file <- file.path(thisPath,thisFile)
conn <- dbConnect(RSQLite::SQLite(), dbname = db_file)
```

```{r}
# List all tables in the database
tables <- dbListTables(conn)
print(tables)
```

```{r}
# Read a specific table into R as a data frame
# Replace 'table_name' with the actual table name from your database
table_name <- "Pixel_export"
data_pixel <- dbReadTable(conn, table_name) %>% 
dplyr::select(pixel_id,AGENT_NO, Lat,Lon) 

print(head(data_pixel))
```

```{r}
# Read a specific table into R as a data frame
# Replace 'table_name' with the actual table name from your database
table_name <- "GCM_export"
data_gcm <- dbReadTable(conn, table_name) %>% 
dplyr::select(gcm_id,name) %>% 
dplyr::rename(GCM=name)

print(head(data_gcm))
```

```{r}
# Read a specific table into R as a data frame
# Replace 'table_name' with the actual table name from your database
table_name <- "RCP_export"
data_rcp <- dbReadTable(conn, table_name) %>% 
  dplyr::select(rcp_id,name) %>% 
dplyr::rename(RCP=name)

print(head(data_rcp))
```

```{r}
# Read a specific table into R as a data frame
# Replace 'table_name' with the actual table name from your database
table_name <- "TimeSlice_export"
data_time_slice <- dbReadTable(conn, table_name) %>% dplyr::select(time_slice_id,name) %>% 
dplyr::rename(TimeSlice=name)

print(head(data_time_slice))
```


```{r}
# Read a specific table into R as a data frame
# Replace 'table_name' with the actual table name from your database
table_name <- "Simulation_export"
data_output <- dbReadTable(conn, table_name)

print(head(data_output))
```

# Merge coodinates and data
```{r}
data_work <- data_output %>%
  inner_join(data_pixel, by = "pixel_id") %>%
  inner_join(data_gcm, by = "gcm_id") %>%
  inner_join(data_rcp, by = "rcp_id") %>%
  inner_join(data_time_slice, by = "time_slice_id") %>%
  dplyr::select(-ends_with("_id")) %>%
  inner_join(regions_csv)


head(data_work)
tail(data_work)
```


# Plot results
```{r}
library(dplyr)
library(ggplot2)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
```
```{r}
# Function to classify Yield into categories based on percentiles
categorize_yield <- function(yield) {
  cut(yield,
      breaks = c(-Inf, 0.25, 0.5, 0.75, Inf),
      labels = c("Very Low", "Low", "High", "Very High"),
      right = FALSE
  )
}
```


# Find quantiles
```{r}

quartiles <- data_work %>%
  ungroup() %>%
   filter(RCP == "RCPpast") %>%
  group_by(Crop) %>%
  # Dynamically calculate quartiles for each group
  summarise(
    Q1 = quantile(ProductFresh_kgPerHa, 0.10),
    Q2 = quantile(ProductFresh_kgPerHa, 0.5),
    Q3 = quantile(ProductFresh_kgPerHa, 0.90))


df <- data_work %>%
  group_by(Lat,Lon, Crop, Irrigation, RCP, TimeSlice, AGENT_NO, REGC2015_N) %>%
  summarise(Yield=median(ProductFresh_kgPerHa)) %>%
  ungroup() %>%
  inner_join(quartiles, by="Crop") %>%
  group_by(Crop) %>%
  # Dynamically calculate quartiles for each group
  mutate(
    # Q1 = quantile(Yield, 0.10),
    # Q2 = quantile(Yield, 0.5),
    # Q3 = quantile(Yield, 0.90),
    Category = case_when(
      Yield <= Q1 ~ "Very Low",
      Yield > Q1 & Yield <= Q2 ~ "Low",
      Yield > Q2 & Yield <= Q3 ~ "High",
      Yield > Q3 ~ "Very High"
    ) ) %>%
  ungroup() %>%
  mutate(
    LegendLabel  = case_when(
      Category == "Very Low" ~ paste("Very Low (≤", round(Q1, 0), ")", sep = ""),
      Category == "Low" ~ paste("Low (", round(Q1, 0), "-", round(Q2, 0), ")", sep = ""),
      Category == "High" ~ paste("High (", round(Q2, 0), "-", round(Q3, 0), ")", sep = ""),
      Category == "Very High" ~ paste("Very High (>", round(Q3, 0), ")", sep = "")
    )
  )

head(df)
```


# map preparation
```{r}
# Get New Zealand map using rnaturalearth
nz_map <- ne_countries(scale = "medium", country = "New Zealand", returnclass = "sf")

# Define the bounding box for New Zealand (approximate coordinates)
nz_bbox <- c(xmin = 166, xmax = 179, ymin = -47, ymax = -34)
```


# Plot using continuous values
```{r}
thisCrop <- unique(df$Crop)

for (i in 1:length(thisCrop)) {
  
  
  print(thisCrop[i])
  
  # prepare this df
  df_crop <- df %>% filter(Crop == thisCrop[i]) %>% 
  mutate(RCP=factor(RCP, levels= c("RCPpast", "RCP4.5", "RCP6.0","RCP8.5")))%>% 
  mutate(TimeSlice=factor(TimeSlice, levels= c("Baseline", "Midcentury", "Endcentury")))
  
  # create plot
  p <- ggplot() +
  # Add New Zealand map contours
  geom_sf(data=nz_map, fill = NA, color = "black", inherit.aes = FALSE) +
  # Add the median product data
  geom_point(
    data = df_crop,
    aes(x = Lon, y = Lat, color = Yield),
    shape=15, 
    size = 0.5
  ) +
  facet_grid(Irrigation ~ RCP + TimeSlice) + # Facet by RCP and Rainfed/Irrigated
  scale_color_viridis_c(name = "kg/ha") +
  theme_minimal() +
  labs(
    title = paste0(thisCrop[i], " - Median yield across New Zealand") ,
    x = "Longitude",
    y = "Latitude"
  )+
  coord_sf(xlim = c(nz_bbox["xmin"], nz_bbox["xmax"]), ylim = c(nz_bbox["ymin"], nz_bbox["ymax"])) +
    theme(text = element_text(size = 7),
          axis.text.x = element_text(angle = 45, hjust = 1) )
  
  print(p)
  
  
  thisOutFolder <- file.path(thisPath,"MapResults") 
  
  
  # Create folder if it doesn't exist
if (!dir.exists(thisOutFolder)) {
  dir.create(thisOutFolder, recursive = TRUE)
}

 
  
# Save the plot as a JPEG file with 300 DPI
ggsave(filename = file.path(thisOutFolder,paste0("Map_",thisCrop[i],".jpg")),
       plot = p,
       width = 6,    # Width in inches
       height = 4,   # Height in inches
       dpi = 300)
  
}


```

# Plot using yield classes
```{r}
fontSize <- 8

thisCrop <- unique(df$Crop)

for (i in 1:length(thisCrop)) {
  
  
  print(thisCrop[i])
  
  # prepare this df
  df_crop <- df %>% filter(Crop == thisCrop[i]) %>% 
  mutate(RCP=factor(RCP, levels= c("RCPpast", "RCP4.5", "RCP6.0","RCP8.5")))%>% 
  mutate(TimeSlice=factor(TimeSlice, 
                          levels= c("Baseline", "Midcentury", "Endcentury")))%>% 
  mutate(Category=factor(Category, 
                         levels= c("Very High", "High", "Low","Very Low"))) %>% 
  mutate(LegendLabel=factor(LegendLabel))
  
  legend_label <- unique(df_crop$LegendLabel)
  
  # create plot
  p <- ggplot() +
  # Add New Zealand map contours
  geom_sf(data=nz_map, fill = NA, color = "black", inherit.aes = FALSE) +
  # Add the median product data
  geom_point(
    data = df_crop,
    aes(x = Lon, y = Lat, color = Category),
    shape=15, 
    size = 0.5,
    alpha = 0.5
  ) +
  facet_grid(Irrigation ~ RCP + TimeSlice) + # Facet by RCP and Rainfed/Irrigated
  scale_color_manual(
    values = c("Very Low" = "red", 
               "Low" = "orange", 
               "High" = "yellow", 
               "Very High" = "green"),
    guide = guide_legend(override.aes = list(size = 5)) # Make legend boxes larger
  )+
  theme_minimal() +
  labs(
    title = paste0(thisCrop[i], " - Yield category ranges across New Zealand\n\n",
                   legend_label[2],", ",legend_label[1],", ",
                   legend_label[3],", ",legend_label[4],
                   "\n\n ------------DRAFT IN CONFIDENCE------------") ,
    x = "Longitude",
    y = "Latitude"
  ) +
  coord_sf(xlim = c(nz_bbox["xmin"], nz_bbox["xmax"]), 
           ylim = c(nz_bbox["ymin"], nz_bbox["ymax"])) +
    theme(text = element_text(size = fontSize),
          axis.text.x = element_text(angle = 45, hjust = 1) )
  
  print(p)
  
  
  thisOutFolder <- file.path(thisPath,"MapResults") 
  
  
  # Create folder if it doesn't exist
if (!dir.exists(thisOutFolder)) {
  dir.create(thisOutFolder, recursive = TRUE)
}

 
  
# Save the plot as a JPEG file with 300 DPI
ggsave(filename = file.path(thisOutFolder,paste0("CategMap_",thisCrop[i],".jpg")),
       plot = p,
     #  width = 8,    # Width in inches
     #  height = 4,   # Height in inches
       dpi = 300)
  
}


```

# Create difference maps
```{r}
diff_df <- df %>%
  tidyr::spread(TimeSlice, Yield) %>%
  group_by(Lat,Lon,Crop,REGC2015_N, Irrigation) %>%
  mutate(RCP=factor(RCP), Irrigation=factor(Irrigation)) %>%
  mutate(BaselineValue = ifelse(is.na(Baseline), 
                           Baseline[RCP == "RCPpast"], 
                           Baseline)) %>%
  mutate(DiffAbs_mid=Midcentury-BaselineValue,
         DiffAbs_end=Endcentury-BaselineValue,
         DiffRel_mid=round(100*(DiffAbs_mid/BaselineValue),1),
         DiffRel_end=round(100*(DiffAbs_end/BaselineValue),1)) %>%
  dplyr::select(-Baseline) %>%
  filter(RCP != "RCPpast")


head(diff_df)
```


```{r, fig.height=15}
diff_plot <- diff_df %>%
  tidyr::gather("VarName","VarValue",Endcentury:DiffRel_end) %>%
  filter(VarName %in% c("DiffAbs_mid", "DiffAbs_end")) %>%
  mutate(VarName = factor(VarName,levels=c("DiffAbs_mid", "DiffAbs_end"),
                        labels=c("Mid-century","End-of-century")))%>%
  na.omit()
```

```{r, fig.height=25}

crop_names <- unique(diff_plot$Crop)

for(i in 1:length(crop_names)) {
  
  print(crop_names[i])
  

p <- diff_plot %>%
    filter(Crop == crop_names[i]) %>%
  ggplot(aes(x=RCP, y=VarValue, colour=VarName)) + 
  
  geom_jitter(alpha=0.1,
              position = position_jitterdodge(jitter.width = 0.3, 
                                              dodge.width = 0.8))+
  geom_boxplot(alpha=0.5) +
  facet_wrap(REGC2015_N~Irrigation) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "darkgrey", size = 1)+
  theme(text = element_text(size = 20),
          axis.text.x = element_text(angle = 45, hjust = 1) )+
  ylab("Absolute change in yield from baseline (kg/ha)")+
  guides(color = guide_legend(title = NULL)) +
  labs(title = paste0(crop_names[i], " - Yield changes across regions\n"))

print(p)

# Save the plot as a JPEG file with 300 DPI
ggsave(filename = file.path(thisOutFolder,paste0("GraphReg_",crop_names[i],".jpg")),
       plot = p,
     #  width = 8,    # Width in inches
     #  height = 4,   # Height in inches
       dpi = 300)


}
```

# Plot diff category maps
```{r}


diff_rel_plot <- diff_df %>%
  tidyr::gather("VarName","VarValue",Endcentury:DiffRel_end) %>%
  filter(VarName %in% c("DiffRel_mid", "DiffRel_end")) %>%
  mutate(VarName = factor(VarName,levels=c("DiffRel_mid", "DiffRel_end"),
                        labels=c("Mid-century","End-of-century")))%>%
  na.omit() %>% 
  group_by(Crop) %>%
  # Dynamically calculate quartiles for each group
  mutate(
    Category2 = case_when(
      VarValue < -100 ~ "> 100% down",
      VarValue >= -100 & VarValue <= -50 ~ "100 to 50% down",
      VarValue >= -50 & VarValue <= -5 ~ "50 to 5% down",
      VarValue >= -5 & VarValue <= 5 ~ "Unchanged",
       VarValue >= 5 & VarValue <= 50 ~ "5 to 50 up%",
      VarValue >= 50 & VarValue <= 100 ~ "50 to 100% up",
      VarValue > 100 ~ "> 100% up"
    ))



fontSize <- 8

thisCrop <- unique(diff_rel_plot$Crop)


for (i in 1:length(thisCrop)) {
  
  
  print(thisCrop[i])
  
  # prepare this df
  df_crop <- diff_rel_plot %>% filter(Crop == thisCrop[i]) %>% 
  mutate(RCP=factor(RCP, levels= c("RCP4.5", "RCP6.0","RCP8.5"))) %>% 
  mutate(Category2=factor(Category2, 
                          levels= c("> 100% down", "100 to 50% down",
                                    "50 to 5% down","Unchanged",
                                    "5 to 50 up%","50 to 100% up", 
                                    "> 100% up")))
  
  # create plot
  # create plot
  p <- ggplot() +
  # Add New Zealand map contours
  geom_sf(data=nz_map, fill = NA, color = "black", inherit.aes = FALSE) +
  # Add the median product data
  geom_point(
    data = df_crop,
    aes(x = Lon, y = Lat, color = Category2),
    shape=15, 
    size = 0.5,
    alpha = 0.5
  ) +
  facet_grid(Irrigation ~ RCP + VarName) + # Facet by RCP and Rainfed/Irrigated
  scale_color_manual(
    values = c("> 100% down" = "darkred", 
               "100 to 50% down" = "red",
               "50 to 5% down" = "orange",
               "Unchanged" = 'grey',
               "5 to 50 up%" = "yellow",
               "50 to 100% up" = "green",
               "> 100% up" = "darkgreen"),
     drop = FALSE,
    guide = guide_legend(override.aes = list(size = 5)) # Make legend boxes larger
  )+
  theme_minimal() +
  labs(
    title = paste0(thisCrop[i], " - Yield category ranges across New Zealand\n\n",
                   "\n\n ------------DRAFT IN CONFIDENCE------------") ,
    x = "Longitude",
    y = "Latitude"
  )+
  coord_sf(xlim = c(nz_bbox["xmin"], nz_bbox["xmax"]), 
           ylim = c(nz_bbox["ymin"], nz_bbox["ymax"])) +
    theme(text = element_text(size = fontSize),
          axis.text.x = element_text(angle = 45, hjust = 1) )
  
  print(p)
  
  
  thisOutFolder <- file.path(thisPath,"MapResults") 
  
  
  # Create folder if it doesn't exist
if (!dir.exists(thisOutFolder)) {
  dir.create(thisOutFolder, recursive = TRUE)
}

 
  
# Save the plot as a JPEG file with 300 DPI
ggsave(filename = file.path(thisOutFolder,paste0("DiffRelCatMap_",thisCrop[i],".jpg")),
       plot = p,
       width = 6,    # Width in inches
       height = 4,   # Height in inches
       dpi = 300)
  
}



```

# Plot continuous difference percentage

```{r}


thisCrop <- unique(df$Crop)

for (i in 1:length(thisCrop)) {
  
  
  print(thisCrop[i])
  
  # prepare this df
  df_crop <- diff_rel_plot %>% filter(Crop == thisCrop[i]) %>% 
  mutate(RCP=factor(RCP, levels= c("RCP4.5", "RCP6.0","RCP8.5")))
  
  # create plot
  p <- ggplot() +
  # Add New Zealand map contours
  geom_sf(data=nz_map, fill = NA, color = "black", inherit.aes = FALSE) +
  # Add the median product data
  geom_point(
    data = df_crop,
    aes(x = Lon, y = Lat, color = VarValue),
    shape=15, 
    size = 0.5
  ) +
  facet_grid(Irrigation ~ RCP + VarName) + # Facet by RCP and Rainfed/Irrigated
  scale_color_viridis_c(name = "% of \n baseline") +
  theme_minimal() +
  labs(
    title = paste0(thisCrop[i], " - Median yield across New Zealand") ,
    x = "Longitude",
    y = "Latitude"
  )+
  coord_sf(xlim = c(nz_bbox["xmin"], nz_bbox["xmax"]), ylim = c(nz_bbox["ymin"], nz_bbox["ymax"])) +
    theme(text = element_text(size = 7),
          axis.text.x = element_text(angle = 45, hjust = 1) )
  
  print(p)
  
  
  thisOutFolder <- file.path(thisPath,"MapResults") 
  
  
  # Create folder if it doesn't exist
if (!dir.exists(thisOutFolder)) {
  dir.create(thisOutFolder, recursive = TRUE)
}

 
  
# Save the plot as a JPEG file with 300 DPI
ggsave(filename = file.path(thisOutFolder,paste0("DiffContMap_",thisCrop[i],".jpg")),
       plot = p,
       width = 6,    # Width in inches
       height = 4,   # Height in inches
       dpi = 300)
  
}

```
```{r}
library(patchwork)
library(grid)
library(gtable)
```

# Plot RCPpast only using yield classes
```{r, fig.width=12}

# Function to add a black border around a plot
add_black_border <- function(plot) {
  grob <- ggplotGrob(plot)  # Convert ggplot to grob
  gtable::gtable_add_grob(
    grob,
    grobTree(rectGrob(gp = gpar(fill = NA, col = "black", lwd = 2))),
    t = 1, l = 1, b = nrow(grob), r = ncol(grob)
  )
}




fontSize <- 8

thisCrop <- unique(df$Crop)

for (i in 1:length(thisCrop)) {
  
  
  print(thisCrop[i])
  
  # --------------Graph Baseline Yild categories ------------
  #----------------------------------------------------------
  df_crop <- df %>% 
    filter(RCP == "RCPpast") %>%
    filter(Crop == thisCrop[i]) %>% 
  mutate(RCP=factor(RCP, levels= c("RCPpast", "RCP4.5", "RCP6.0","RCP8.5")))%>% 
  mutate(TimeSlice=factor(TimeSlice, 
                          levels= c("Baseline", "Midcentury", "Endcentury")))%>% 
  mutate(Category=factor(Category, 
                         levels= c("Very High", "High", "Low","Very Low"))) %>% 
  mutate(LegendLabel=factor(LegendLabel))
  
  # Sort labeling order
  legend_label <- unique(df_crop$LegendLabel)
  l1 <- legend_label[match(TRUE, grepl("Very High", legend_label))]
  l2 <- legend_label[match(TRUE, grepl("High", legend_label))]
  l3 <- legend_label[match(TRUE, grepl("Low", legend_label))] 
  l4 <- legend_label[match(TRUE, grepl("Very Low", legend_label))]
  
  # create plot
  p1 <- ggplot() +
  # Add New Zealand map contours
  geom_sf(data=nz_map, fill = NA, color = "black", inherit.aes = FALSE) +
  # Add the median product data
  geom_point(
    data = df_crop,
    aes(x = Lon, y = Lat, color = Category),
    shape=15, 
    size = 0.5,
    alpha = 0.5
  ) +
  facet_wrap(Irrigation~., ncol=1) + # Facet by RCP and Rainfed/Irrigated
  scale_color_manual(
    name = "Yield category",
    values = c("Very Low" = "red", 
               "Low" = "orange", 
               "High" = "yellow", 
               "Very High" = "green"),
    guide = guide_legend(override.aes = list(size = 5)) # Make legend boxes larger
  )+
  theme_minimal() +
  labs(
    title = paste0(thisCrop[i],"\n\n",
                   l1," | ",l2,"\n",
                   l3," | ",l4,
                   "\n\n ------------BASELINE YIELD ------------") ,
    x = "Longitude",
    y = "Latitude"
  ) +
  coord_sf(xlim = c(nz_bbox["xmin"], nz_bbox["xmax"]), 
           ylim = c(nz_bbox["ymin"], nz_bbox["ymax"])) +
    theme(text = element_text(size = fontSize),
          axis.text.x = element_text(angle = 45, hjust = 1) ) +
  theme(legend.position = "left") +
  theme(
    plot.title = element_text(hjust = 0.5) # Center the title
  ) 
  
   p1_border <- add_black_border(p1)
  
  
  # --------------Graph Categorical yield changes ------------
  #----------------------------------------------------------
  # prepare this df
  df_crop <- diff_rel_plot %>% filter(Crop == thisCrop[i]) %>% 
  mutate(RCP=factor(RCP, levels= c("RCP4.5", "RCP6.0","RCP8.5"))) %>% 
  mutate(Category2=factor(Category2, 
                          levels= c("> 100% down", "100 to 50% down",
                                    "50 to 5% down","Unchanged",
                                    "5 to 50 up%","50 to 100% up", 
                                    "> 100% up"))) %>%
  filter(RCP == "RCP8.5" & VarName == "End-of-century" |
         RCP == "RCP6.0" & VarName == "End-of-century"  |
         RCP == "RCP4.5" & VarName == "Mid-century"  
           )
  
  
  p2 <- ggplot() +
  # Add New Zealand map contours
  geom_sf(data=nz_map, fill = NA, color = "black", inherit.aes = FALSE) +
  # Add the median product data
  geom_point(
    data = df_crop,
    aes(x = Lon, y = Lat, color = Category2),
    shape=15, 
    size = 0.5,
    alpha = 0.5
  ) +
  facet_grid(Irrigation ~ RCP + VarName) + # Facet by RCP and Rainfed/Irrigated
  scale_color_manual(
    name = "Yield change (%)",
    values = c("> 100% down" = "darkred", 
               "100 to 50% down" = "red",
               "50 to 5% down" = "orange",
               "Unchanged" = 'grey',
               "5 to 50 up%" = "yellow",
               "50 to 100% up" = "green",
               "> 100% up" = "darkgreen"),
     drop = FALSE,
    guide = guide_legend(override.aes = list(size = 5)) # Make legend boxes larger
  )+
  theme_minimal() +
  labs(x = "Longitude",y = "Latitude", 
       title = "\n\n -----------YIELD CHANGE IN THE FUTURE (% BASELINE) ------------")+
  coord_sf(xlim = c(nz_bbox["xmin"], nz_bbox["xmax"]), 
           ylim = c(nz_bbox["ymin"], nz_bbox["ymax"])) +
    theme(text = element_text(size = fontSize),
          axis.text.x = element_text(angle = 45, hjust = 1) ) +
  theme(
    plot.title = element_text(hjust = 0.5) # Center the title
  ) 

  
  p2_border <- add_black_border(p2)
  
  # combine plots
  combined_plot <- p1 | p2
  
  print(combined_plot)
  
  # thisOutFolder <- file.path(thisPath,"MapResults") 
  
  
  # Create folder if it doesn't exist
# if (!dir.exists(thisOutFolder)) {
#   dir.create(thisOutFolder, recursive = TRUE)
# }

 
  
# Save the plot as a JPEG file with 300 DPI
# ggsave(filename = file.path(thisOutFolder,paste0("CategMap_",thisCrop[i],".jpg")),
#        plot = p,
#      #  width = 8,    # Width in inches
#      #  height = 4,   # Height in inches
#        dpi = 300)
  
}


```

```{r}
# Run a custom SQL query (optional)
query <- "SELECT * FROM your_table_name LIMIT 10"
query_result <- dbGetQuery(conn, query)
print(query_result)
```

```{r}
# Disconnect from the database
dbDisconnect(conn)
```


