---
title: "R Notebook"
output: html_notebook
---

# Analysis of Deropapy behaviour (sensibility tests)

```{r, LoadLibs}
library("data.table")
library("RSQLite")
library("tidyverse")
library("plotly")
library("GGally")
```

# Find db to be used
```{r}
# working wit develop base sim for now
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
getwd()
```

```{r}
# 1. Find files
dbFileList <- list.files(pattern='Deropapy.db$', full.names = TRUE,include.dirs = FALSE,no..= FALSE)
print(dbFileList)
```
Function to get data from db

```{r}

# 2. Extract data
GetApsimNGTable <- function(dbLoc, table) 
{
  connection <- dbConnect(SQLite(), dbname = dbLoc, flags = SQLITE_RW) #The connection to the database
  table <- dbReadTable(connection, table, row.names=NULL) # The data in a table
  dbDisconnect(connection)
  return(table)
}
```

# Get data
```{r}
info_out_raw <- data.table()
list_of_dts <- list()

# which table to extract?
#TableName <- "ReportSensitivity" # annual outputs
TableName <- c("Output") # annual outputs

for (i in 1:length(TableName)) {
  
  db.name <- dbFileList
  
  db.full.path <- file.path(db.name)
  
  # connect to the SQLite db file    
  con <- dbConnect(SQLite(), dbname = db.full.path, flags = SQLITE_RW)
  
  # get a list of all tables from db
  alltables <- dbListTables(con)
  alltables
  dbDisconnect(con)
  #gc()
  
  # get table as a `data.frame`
  temp1 <- data.table()
  temp1 <- GetApsimNGTable(db.full.path, TableName[i])
  
 # info_out_raw <- rbind(info_out_raw, temp1)
  
  list_of_dts[[i]] <- temp1
  
}

#summary(info_out_raw)
summary(list_of_dts)
list_of_dts[[1]]
```
# Create formated version of data
```{r}

# columns as factor 
columns_as_factors <- c("Experiment","Crop","Location",
                        "Irrigation","GCM","RCP","TimeSlice","SoilStamp", 
                        "Lat", "Lon", "Zone", "AGENT_NO", "MGMT","SoilType")


info_out_work <- list_of_dts[[1]] %>% 
  mutate(MGMT = factor(ifelse(is.na(MGMT),"Basic",MGMT))) %>%
  mutate(
    Irrigation = case_when(
      is.na(Irrigation) & MGMT == "Basic" ~ "Rainfed",
      is.na(Irrigation) & MGMT == "FF" ~ "Rainfed",
      is.na(Irrigation) & MGMT == "Irrig" ~ "Irrigated",
      is.na(Irrigation) & MGMT == "FFandIrrig" ~ "Irrigated",
      TRUE ~ Irrigation # Keep existing values
    )) %>%
  mutate(across(all_of(columns_as_factors), factor))%>%
  mutate(ReportDate=as.Date(ymd_hms(ReportDate)))%>%
  filter(str_detect(Experiment, "Testing|Sensitivity")) # select sensitivity runs only
  

summary(info_out_work)
```

# set crops
```{r}
thisCropPerennials <- c("GrapeVine","Avocado","Macadamia","Lemon")
thisCropAnnuals <- c("Maize","Wheat","Hemp","OSR")
seleted_yield_columns <- c("Product_kgPerHa")
```

# Create subset of results

```{r, fig.height=14}

info_out_work_subset <- info_out_work %>%
  dplyr::filter(Crop %in% c(thisCropAnnuals,thisCropPerennials))  %>%
  dplyr::select(columns_as_factors, seleted_yield_columns, "Year")  %>%
  dplyr::mutate(RCP = "RCPpast", RCP=factor(RCP)) # climate files from CMIP5 were used 

summary(info_out_work_subset)
```

```{r, fig.height=16}
info_out_work_subset %>%
  tidyr::gather(VarName,VarValue, seleted_yield_columns) %>%
  ggplot(aes(x=Irrigation,y=VarValue, colour=Irrigation)) +
  geom_boxplot() +
  geom_point(position = position_dodge(width = 0.75)) +
  facet_wrap(Crop~VarName+SoilType, scales="free")
```

```{r, fig.height=16}
info_out_work_subset %>%
  filter(MGMT=="Basic") %>%
  tidyr::gather(VarName,VarValue, seleted_yield_columns) %>%
  ggplot(aes(x=Location,y=VarValue, colour=interaction(Irrigation))) +
  geom_boxplot()+
  geom_point(position = position_jitter(width = 0.1, height = 1)) +
  facet_wrap(Crop~VarName, scales="free")+
  scale_y_continuous(limits = c(0, NA)) +
  coord_flip()
```




















# Check yield PERENNIALS
```{r, fig.width=8}
thisDF <- info_out_work %>%
  dplyr::filter(Crop==thisCropPerennials) %>%
  dplyr::select(columns_as_factors, seleted_yield_columns) #%>%
 # dplyr::filter(RCP != "ERA") 

thisDF %>%
  tidyr::gather(VarName,VarValue, seleted_yield_columns) %>%
  ggplot(aes(x=RCP,y=VarValue, colour=Irrigation)) +
  geom_boxplot() +
  geom_point(position = position_dodge(width = 0.75)) +
  facet_grid(Crop~VarName)
```



# Create formated version of data
```{r}

# columns as factor 
# columns_as_factors <- c("Experiment","Crop","GCM","RCP","TimeSlice","SoilStamp", "Lat", "Lon", "Zone", "ClimateSensCO2",     "ClimateSensTemp",    "ClimateSensRain", "AGENT_NO")

columns_as_factors <- c("Experiment","Crop","Location",
                        "Irrigation","GCM","RCP","TimeSlice","SoilStamp", 
                        "Lat", "Lon", "Zone", "AGENT_NO")

info_out_work <- list_of_dts[[1]]  %>% 
  mutate(across(all_of(columns_as_factors), factor))%>%
  mutate(ReportDate=as.Date(ymd_hms(ReportDate)))%>%
  mutate(Year=as.numeric(Year))

summary(info_out_work)
```


```{r}
thisCropPerennials <- c("Grapevine","Avocado","Macadamia","Lemons")
thisCropAnnuals <- c("Maize","Wheat","Hemp","OSR")
seleted_yield_columns <- c("AboveGround_kgPerHa", "Product_kgPerHa")
#selected_sens_vars <- c()
```

#Check sensitivity

```{r, fig.height=14}
thisDf <- info_out_work %>%
  tidyr::gather(VarName,VarValue, seleted_yield_columns)

thisDf %>%
  ggplot(aes(x=Year, y=VarValue))+
  geom_point(aes(colour=Irrigation))+
 # geom_line(aes(colour=Crop)) +
  facet_wrap(Crop~VarName, scales="free", ncol=2)


```
#Check sensitivity

```{r, fig.width=11}
thisDf <- info_out_work %>%
  dplyr::filter(Experiment=="SensitivityTemp")  %>%
  tidyr::gather(VarName,VarValue, seleted_yield_columns)

thisDf %>%
  ggplot(aes(x=Weather.MeanT, y=VarValue))+
  geom_point(aes(colour=Crop))+
  geom_line(aes(colour=Crop)) +
  facet_wrap(VarName~., scales="free", ncol=2)


```

#Check sensitivity

```{r, fig.width=11}
thisDf <- info_out_work %>%
  dplyr::filter(Experiment=="SensitivityRain")  %>%
  tidyr::gather(VarName,VarValue, seleted_yield_columns)

thisDf %>%
  ggplot(aes(x=Rainfall_Cum, y=VarValue))+
  geom_point(aes(colour=Crop))+
  geom_line(aes(colour=Crop)) +
  facet_wrap(VarName~., scales="free", ncol=2)


```

# Create formated version of data
```{r}

# columns as factor 
  columns_as_factors <- c("Experiment","Crop","Location", "ClimateSensTemp")


info_out_work <- list_of_dts[[2]]  %>% 
  mutate(across(all_of(columns_as_factors), factor))%>%
  mutate(ReportDate=as.Date(ymd_hms(Clock.Today)))

summary(info_out_work)
```

```{r, fig.width=11}
thisDf <- info_out_work

thisDf %>%
  ggplot(aes(x=Weather.MinT, y=DEROPAPY.Leaf.FrostFraction))+
  geom_point(aes(colour=Crop))+
  geom_line(aes(colour=Crop)) 


```
